config/routes.rb
Blog2::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'posts#index'
  devise_for :users

  resources :axes

  resources :users

  resources :posts do
    resources :comments

 end
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :authenticate_user!
end

app/controllers/axes_controller.rb
class AxesController < ApplicationController
  require 'Axis/axis'

  def new 
    @axis = Axis.new
  end

  def create
    @axis = Axis.new axis_params
  end

private 
  def axis_params
    ret_params = params.require(:axis).permit(:attackinfintry, :attackartillery, :attacktanks , :attackbombers , :attackfighters, 
                :defendinfintry , :defendartillery , :defendtanks , :defendfighters, :defendbombers)
    ret_params
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
   
    @post = Post.find_by_id(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
    @comment.save
    
  end

  def show
  end


private 
  def comment_params
    ret_params = params.require(:comment).permit(:email, :content, :post_id)
    ret_params[:email]=current_user.email 
    ret_params
  end

end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    
    @post = Post.new(post_params)
    
    if @post.save
      redirect_to @post, notice: 'post created'
    else
      render action: 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private 
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
     ret_params = params.require(:post).permit(:name, :title, :content, :user_id)
     ret_params['user_id']= current_user.id
     ret_params
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end


  private 
    def user_params 
      usr_params = params.require(:user).permit(:email, :created_at)
      usr_params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/axis_helper.rb
module AxisHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_controller_helper.rb
module PostsControllerHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/axes/create.html.erb
<% @axis.total %>

app/views/axes/new.html.erb
 <%= form_for(@axis) do |f| %>
 <div class="field">
    <%= f.label :attackinfintry %><br>
    <%= f.text_field :attackinfintry %>
  </div>
  <div class="field">
    <%= f.label :attackartillery %><br>
    <%= f.text_field :attackartillery %>
  </div>
  <div class="field">
    <%= f.label :attacktanks %><br>
    <%= f.text_area :attacktanks %>
  </div>
   <div class="field">
    <%= f.label :attackfighters %><br>
    <%= f.text_field :attackfighters %>
  </div>
  <div class="field">
    <%= f.label :attackbombers %><br>
    <%= f.text_field :attackbombers %>
  </div>
  <div class="field">
    <%= f.label :defendinfintry %><br>
    <%= f.text_area :defendinfintry %>
  </div>
    <div class="field">
    <%= f.label :defendartillery %><br>
    <%= f.text_area :defendartillery %>
  </div>
   <div class="field">
    <%= f.label :defendtanks %><br>
    <%= f.text_field :defendtanks %>
  </div>
  <div class="field">
    <%= f.label :defendfighters %><br>
    <%= f.text_field :defendfighters %>
  </div>
  <div class="field">
    <%= f.label :defendbombers %><br>
    <%= f.text_area :defendbombers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
  <h1>  ERIK'S BLOG  </h1>

<div class = "container">
  <%= link_to 'Home', posts_path %>
  <%= link_to 'Users', users_path %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<%= render 'layouts/header' %>

<html>
<head>
  <title>Blog2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
 <%= form_for(@post) do |f| %>
 <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class = "container">
 

    
      <% @posts.each do |post| %>

        <h3> Title:  <%= post.name %></h3> 
        <%= post.title %>
        <h3> Content </h3>
        <%= truncate(post.content, length: 300) %>
        <div>
          <%= link_to 'Show', post %>
        </div>
        <hr Width= "100%">
      <% end %> 
  </table>
  <br>

</div>

app/views/posts/new.html.erb
<div class = 'container' >
    <h1>New post</h1>
    <%= render 'form' %>
    <% else %>
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class = "container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @post.name %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @post.content %>
  </p>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>


  <h2>Add a comment:</h2>
  <%= form_for([@post, @post.comments.build]) do |f| %>
   
    <div class="field">
      <%= f.label :content %><br/>
      <%= f.text_area :content %>
    </div>
  <p> 
   
    

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  <h2>Comments</h2>
  <% if @post.comments.length > 0 %>
    <% @post.comments.each do |comment| %>
      <p>
        <b>Author:</b>
        <%= comment.email %>
      </p>

      <p>
        <b>Comment:</b>
        <%= comment.content %>
      </p>
    <% end %>
  <% else %>
    <h3>No comments have been posted yet.</h3>
  <% end %>
</div>

app/views/users/index.html.erb
<div class= 'container'>
  <table style='margin: 0px auto;'>
      <% @users.each do |user| %>
        <tr>
          <td> Email: <%= user.email %></td>

          <td> <%= link_to "User Profile", user %>

          <td>Date Created: <%= user.created_at%></td>

          <td>
            Posts:
           <% user.posts.each do |post| %>

              <%= post.title %>
           <%end%>
          </td>
    <%end%>
  </table>  
</div>

 

app/views/users/show.html.erb
<%= @user.email %>
<% @user.posts.each do |post| %>
  <%= post.title %>
  <% end %>